# Lab | Matplotlib & Seaborn

#### Import all the necessary libraries here:

In [1]:
# Libraries
import numpy as np

## Challenge 1

#### The data we will use in this challenge is:

In [17]:
x = np.arange(0, 100)
y = x*2
z = x**2

In [18]:
print(type(x))
print(x.shape)
print(z)
print(y)
print(z)

<class 'numpy.ndarray'>
(100,)
[   0    1    4    9   16   25   36   49   64   81  100  121  144  169
  196  225  256  289  324  361  400  441  484  529  576  625  676  729
  784  841  900  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 1681
 1764 1849 1936 2025 2116 2209 2304 2401 2500 2601 2704 2809 2916 3025
 3136 3249 3364 3481 3600 3721 3844 3969 4096 4225 4356 4489 4624 4761
 4900 5041 5184 5329 5476 5625 5776 5929 6084 6241 6400 6561 6724 6889
 7056 7225 7396 7569 7744 7921 8100 8281 8464 8649 8836 9025 9216 9409
 9604 9801]
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198]
[   0    1    4    9   16   25   36   49   64   81  100  121  144  169
  196  225  256  289  324  361  400  441  484  529  576  625  676  729
  784  841  900  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 1681
 1764 1849 1936 2025 2116 2209 2304 2401 2500 2601 2704 2809 2916 3025
 3136 3249 3364 3481 3600 3721 3844 3969 4096 4225 4356 4489 4624 4761
 4900 5041 5184 5329 5476 5625 5776 5929 6084 6241 6400 6561 6724 6889
 7056 7225 7396 7569 7744 7921 8100 8281 8464 8649 8836 9025 9216 9409
 9604 9801]

#### Plot (x, y) and (x, z).
There are 2 ways of doing this. Do in both ways.

**Hint**: Check out the nrows, ncols and index arguments of subplots. 

Also, play around with the linewidth and style. Use the ones you're most happy with.

In [19]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
# Method 1

In [26]:
#plt.plot(x, y, label='linear')
#plt.show() --> si queremos ver script en Visual Studio Code, sin este comando no podriamos ver el gráfico

In [ ]:
# Method 1

In [ ]:
df = pd.DataFrame({'x':x, 'y':y, 'z':z})
df.plot('x', 'y', kind='line', linestyle=':', linewidth=2)
df.plot('x', 'z', kind='line', linestyle=':', linewidth=2)

#### Use plt.subplots(nrows=1, ncols=2) to create the plot.

In [ ]:
# Method 2

In [ ]:
#fig = plt.figure()
#axs = plt.axes()
fig, axs = plt.subplots(ncols = 2,
                       nrows = 1)
axs[0].plot(x, y)                    
axs[1].plot(x, z)

#### Use your previous code but now, resize your plot.
**Hint**: Add the figsize argument in plt.subplots().

If you want, try to add a title to the plot or even axes labels. You can also play with the fontweight and fontsize of the titles and labels.

In [ ]:
# your code here
fig, axs = plt.subplots(ncols = 2,
                       nrows = 1,
                       figsize = (10, 5))
axs[0].plot(x, y)                    
axs[1].plot(x, z)

axs[0].set(xlabel='x',
           ylabel='y',
           title='Linear growth')
axs[1].set(xlabel='x',
           ylabel='z',
           title='Exponential growth')

# Alternative to set labels and title, with formatting

axs[0].set_title('Linear growth', fontsize=10, fontweight='bold')
axs[0].set_xlabel('X', fontsize=10, fontweight='light')
axs[0].set_ylabel('Y', fontsize=10, fontweight='light')

axs[1].set_title('Exponential growth', fontsize=10, fontweight='bold')
axs[1].set_xlabel('X', fontsize=10, fontweight='light')
axs[1].set_ylabel('Z', fontsize=10, fontweight='light')

# Adjust the space between subplots
plt.subplots_adjust(wspace=0.4)

#### Now you will have to plot both $y=x^2$ and $y=e^x$ in the same plot. Create two subplots and use a normal scale in the first one and a logarithmic scale in the second one.
**Hint**: Use `set_xscale` and `set_yscale`.

In [ ]:
# your code here
# Define the variables:

y1 = x*2
y2 = np.exp(x)

# Create subplots:

fig, axs = plt.subplots(ncols = 2,
                       nrows = 1,
                       figsize = (10, 5))
axs[0].plot(y1, y2)                    
axs[1].plot(y1, y2)

# Apply logaritmic scale to 2nd plot

axs[1].set_xscale("log")
axs[1].set_yscale("log")

#### As a bonus challenge, try to add a legend to the plot.

In [ ]:
# your code here
fig, axs = plt.subplots(ncols = 2,
                       nrows = 1,
                       figsize = (10, 5))

# Plotting data with labels for legend
line1, = axs[0].plot(x, y, label='Linear growth')  # Ensure line1 is assigned
line2, = axs[1].plot(x, z, label='Exponential growth')  # Ensure line2 is assigned

# Set labels
axs[0].set(xlabel='x',
           ylabel='y')
axs[1].set(xlabel='x',
           ylabel='z')

# Adjust the space between subplots
plt.subplots_adjust(wspace=0.4)

# Adding legends
axs[0].legend()
axs[1].legend()

## Challenge 2
#### Import the `Fitbit2` dataset and store it in a variable called `fitbit`. You can find the dataset in Ironhack's database:
* db: `fitbit`
* table: `fitbit2`

In [ ]:
# your code here
fitbit = pd.read_csv('../Data/fitbit2.csv')
fitbit.head()
#fitbit.info()

#### From the Fitbit data, we want to visually understand:

How the average number of steps change by month. Use the appropriate visualization to show the median steps by month. Is Fitbitter more active on weekend or workdays? All plots must be in the same jupyter notebook cell.

**Hints**:

* Use Months_encoded and Week_or Weekend columns.
* Use matplolib.pyplot object oriented API.
* Set your size figure to 12,4
* Explore plt.sca
* Explore plt.xticks
* Save your figures in a folder called `figures` in your repo.

In [ ]:
# MEDIAN STEPS BY MONTH_ENCODED
# your code here

# Group dataset by month:
df_steps_month = fitbit.groupby(['Months_encoded'])[['Steps']].mean().reset_index()

# Create a list of month names
month_names = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 
               'September', 'October', 'November', 'December']

# Map the 'Months_encoded' to month names
df_steps_month['Month_Name'] = df_steps_month['Months_encoded'].apply(lambda x: month_names[x-1])

# Create the plot
ax1 = df_steps_month.plot(x='Month_Name', y='Steps', kind='bar', figsize=(12,4))

# Set x-axis label and title
ax1.set_xlabel('Month')
ax1.set_ylabel('Average Steps')
ax1.set_title('Average Steps per Month')

# Set minimum value for y-axis
plt.ylim(bottom=5000)

# Save plot
plt.savefig('../Data/plot1.png', transparent=False, dpi=80, bbox_inches="tight", format='png')


# MEDIAN STEPS BY WORK_OR_WEEKEND

# Group dataset by week:
df_steps_weekday = fitbit.groupby(['Work_or_Weekend'])[['Steps']].mean().reset_index()

# Create the plot
ax2 = df_steps_weekday.plot(x='Work_or_Weekend', y='Steps', kind='bar', figsize=(12,4))

# Change the name of x-axis labels
plt.xticks([0, 1], ["Weekend" , "Work"])

# Set x-axis label and title
ax2.set_xlabel('Wekday_type')
ax2.set_ylabel('Average Steps')
ax2.set_title('Average Steps per Weekday_type')

# Set minimum value for y-axis
plt.ylim(bottom=10000)

# Save plot
plt.savefig('../Data/plot2.png', transparent=False, dpi=80, bbox_inches="tight", format='png')

#### Write a loop to plot 3 scatter plots of the following features:

* Minutes Lightly Active vs Steps    
* Minutes Very Active vs Steps    
* Minutes Sedentary vs Steps

In [ ]:
# your code here
Minuts_Active_list = ["Minutes Lightly Active", "Minutes Fairly Active", "Minutes Very Active"]
for column in Minuts_Active_list:
    fitbit.plot(x=column, y='Steps', kind='scatter', figsize=(12,4))
    plt.xlabel(column)
    plt.ylabel('Steps')
    plt.title(f'{column} vs Steps')

## Challenge 3

#### Import the `titanic` dataset and store it in a variable called `titanic`. You can find the dataset in Ironhack's database:
* db: `titanic`
* table: `titanic`

In [7]:
# your code here
titanic = pd.read_csv('../Data/titanic.csv')
titanic.head()

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,U0,S
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,U0,S
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,U0,S

#### Explore the titanic dataset using Pandas dtypes.

In [8]:
# your code here
#titanic.info()
titanic.dtypes

PassengerId      int64
Survived       float64
Pclass           int64
Name            object
Gender          object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

#### What are your numerical variables? What are your categorical variables?
**Hint**: Use Pandas select_dtypes.

In [15]:
# NUMERICAL VARIABLES
# your code here
titanic.select_dtypes(include=['int64', 'float64'])
# Exception1: Survived can be considered categorical variable because it represents two categories: Survived, Deceased
# Exception2: Pclass can be also considered as categorical variable

      PassengerId  Survived  Pclass        Age  SibSp  Parch      Fare
0               1       0.0       3  22.000000      1      0    7.2500
1               2       1.0       1  38.000000      1      0   71.2833
2               3       1.0       3  26.000000      0      0    7.9250
3               4       1.0       1  35.000000      1      0   53.1000
4               5       0.0       3  35.000000      0      0    8.0500
...           ...       ...     ...        ...    ...    ...       ...
1304         1305       NaN       3  29.513190      0      0    8.0500
1305         1306       NaN       1  39.000000      0      0  108.9000
1306         1307       NaN       3  38.500000      0      0    7.2500
1307         1308       NaN       3  29.513190      0      0    8.0500
1308         1309       NaN       3  25.315435      1      1   22.3583

[1309 rows x 7 columns]

In [22]:
# CATEGORICAL VARIABLES
# your code here
titanic.select_dtypes(include=['object'])

,Name,Gender,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,U0,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,U0,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,U0,S
...,...,...,...,...,...
1304,"Spector, Mr. Woolf",male,A.5. 3236,U0,S
1305,"Oliva y Ocana, Dona. Fermina",female,PC 17758,C105,C
1306,"Saether, Mr. Simon Sivertsen",male,SOTON/O.Q. 3101262,U0,S
1307,"Ware, Mr. Frederick",male,359309,U0,S
1308,"Peter, Master. Michael J",male,2668,U0,C

#### Set the plot style to classic and the figure size to (12,6).
**Hint**: To set the style you can use matplotlib or seaborn functions. Do some research on the matter.

In [ ]:
# your code here

#### Use the right visulalization to show the distribution of column `Age`.

In [ ]:
# your code here

#### Use subplots and plot the distribution of the `Age`  with bins equal to 10, 20 and 50.

In [ ]:
# your code here

#### How does the bin size affect your plot?

In [ ]:
"""
your comments here
"""

#### Use seaborn to show the distribution of column `Age`.

In [ ]:
# your code here

#### Use the right plot to visualize column `Gender`. There are 2 ways of doing it. Do it both ways.
**Hint**: Use matplotlib and seaborn.

In [ ]:
# Method 1 - matplotlib
# your code here

In [ ]:
# Method 2 - seaborn
# your code here

#### Use the right plot to visualize the column `Pclass`.

In [ ]:
# your code here

#### We would like to have in one single plot the summary statistics of the feature `Age`. What kind of plot would you use? Plot it.

In [ ]:
# your code here

In [ ]:
"""
your comments here
"""

#### What does the last plot tell you about the feature `Age`?

In [ ]:
"""
your comments here
"""

#### Now in addition to the summary statistics, we want to have in the same plot the distribution of `Age`. What kind of plot would you use? Plot it.

In [ ]:
# your code here

#### What additional information does the last plot provide about feature `Age`?

In [ ]:
"""
your comments here
"""

#### We suspect that there is a linear relationship between `Fare` and `Age`. Use the right plot to show the relationship between these 2 features. There are 2 ways, please do it both ways.
**Hint**: Use matplotlib and seaborn.

In [ ]:
# Method 1 - matplotlib
# your code here

In [ ]:
# Method 2 - seaborn
# your code here

#### Plot the correlation matrix using seaborn.

In [ ]:
# your code here

#### What are the most correlated features?

In [ ]:
"""
your comments here
"""

#### Use the most appropriate plot to display the summary statistics of `Age` depending on `Pclass`.

In [ ]:
# your code here

#### Use seaborn to plot the distribution of `Age` based on the `Gender`.
**Hint**: Use Facetgrid.

In [ ]:
# your code here